site_name: ProtStruc Documentation
repo_name: dohlee/protstruc
repo_url: https://github.com/dohlee/protstruc
docs_dir: docs

theme:
  name: material
  font:
    text: Inter
  icon:
    logo: fontawesome/solid/dice-d20
    repo: octicons/mark-github-16
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

plugins:
  - mkdocstrings
  - mkdocs-jupyter
  - search

markdown_extensions:
  - tables
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home:
    - index.md
    - Examples: home/examples.md
  - Getting started:
    - Installation: getting-started/installation.md
    - Tutorials:
      - Pairwise distance matrix: tutorials/pairwise_distance_matrix.ipynb
      - Ramachandran plot: tutorials/ramachandran_plot.ipynb
      - Backbone orientations/translations: tutorials/backbone_orientations_and_translations.ipynb
      - Rotating structures: tutorials/rotating_structures.ipynb
      - Diffusing XYZ coordinates with Gaussian noise: tutorials/diffusing_xyz_coordinates.ipynb
      - Parsing antibody PDB files: tutorials/parsing_antibody_pdb.ipynb
      - Using AntibodyStructureBatch: tutorials/antibody_structure_batch.ipynb
  - API reference:
    - StructureBatch: reference/StructureBatch.md
    - AntibodyStructureBatch: reference/AntibodyStructureBatch.md
    - geometry: reference/geometry.md
    - io: reference/io.md
  
extra_css:
  - css/mkdocs.css