site_name: ProtStruc Documentation
repo_name: dohlee/protstruc
repo_url: https://github.com/dohlee/protstruc
docs_dir: docs

theme:
  name: material
  font:
    text: Roboto
  icon:
    logo: fontawesome/solid/dice-d20
    repo: octicons/mark-github-16
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - tables
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started/installation.md
  - API reference:
    - protstruc.protstruc: reference/protstruc.md
    - protstruc.geometry: reference/geometry.md
    - protstruc.io: reference/io.md
  
extra_css:
  - css/mkdocs.css